name: push

on: push

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: first action
      run: echo "Hello World"

    - name: list files
      run: ls -la

    - name: read file
      run: cat README.md
