name: push

on: push

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
    
  format:
    needs: checkov
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: format
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.8.0
          command: fmt
          args: -recursive

  terraform-validate:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: validate
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.8.0
          command: validate

  terraform-plan:
    needs: terraform-validate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: plan
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.8.0
          command: plan
          args: -out=plan.tfplan
